// Eser veritabanı. Her eser: ad, nadirlik, değer, bölge, dönem, açıklama, araştırma bilgisi, müze kategorisi.
(function () {
  const RARITY = [
    { id: 'COMMON', tr: 'Yaygın', col: '#8f8a80' },
    { id: 'UNCOMMON', tr: 'Sıradışı', col: '#3f9a3a' },
    { id: 'RARE', tr: 'Nadir', col: '#2f6fd0' },
    { id: 'EPIC', tr: 'Destansı', col: '#9440c8' },
    { id: 'LEGENDARY', tr: 'Efsanevi', col: '#e08a10' },
  ];
  const CATS = ['Sikkeler', 'Seramik & Cam', 'Araç & Silah', 'Fosil & Doğa', 'Takı & Süs', 'Yazıt & Mühür', 'Heykel & Figür', 'Gizem'];
  const REGIONS = { orman: 'Eski Orman', magara: 'Küçük Mağara', col: 'Çöl Harabeleri' };

  const A = (id, name, rar, value, region, cat, era, shape, col, desc, lore, extra) =>
    Object.assign({ id, name, rar, value, region, cat, era, shape, col, desc, lore, type: 'artifact' }, extra || {});

  const LIST = [
    // ---------------- ESKİ ORMAN ----------------
    A('bakir_sikke', 'Bakır Sikke', 0, 40, 'orman', 'Sikkeler', 'Orman Krallığı, MÖ 3. yy', 'coin', { a: '#c47a3e', b: '#8e4f24', c: '#e8a565' },
      'Bir yüzünde silik bir meşe ağacı olan eski bir bakır para.',
      'Bu sikkeler Orman Krallığı\'nın pazar yerlerinde kullanılmış. Meşe, krallığın kutsal ağacıydı.'),
    A('pismis_kase', 'Pişmiş Toprak Kase', 0, 35, 'orman', 'Seramik & Cam', 'Tunç Çağı', 'bowl', { a: '#c46a3c', b: '#8f4524', c: '#e39260' },
      'Günlük yemekler için kullanılmış sade bir kase. Kenarında parmak izleri hâlâ duruyor.',
      'Kasenin içindeki kalıntılar buğday ve mercimek yendiğini gösteriyor. Bölgede tarım binlerce yıl önce başlamış.'),
    A('ok_ucu', 'Çakmaktaşı Ok Ucu', 0, 30, 'orman', 'Araç & Silah', 'Cilalı Taş Devri', 'arrowhead', { a: '#6a6476', b: '#3b3644', c: '#9a94a6' },
      'Usta bir el tarafından yontulmuş keskin bir ok ucu.',
      'Çakmaktaşı yakındaki nehir yatağından getirilmiş. Ok uçlarının dağılımı avcıların göç yollarını izliyor.'),
    A('kemik_igne', 'Kemik İğne', 0, 25, 'orman', 'Araç & Silah', 'Yontma Taş Devri', 'needle', { a: '#e8dcc0', b: '#b8a98a', c: '#ffffff' },
      'Hayvan kemiğinden yapılmış, deliği özenle açılmış bir dikiş iğnesi.',
      'Bu iğneyle deri giysiler dikilmiş. İnsanlar soğuk kışlara böyle hazırlanırmış.'),
    A('kil_figur', 'Kil Figürin', 1, 90, 'orman', 'Heykel & Figür', 'Neolitik Dönem', 'figurine', { a: '#c98a5a', b: '#94603a', c: '#e3b083' },
      'Elleri karnında kavuşturulmuş küçük bir bereket figürü.',
      'Bu figürinler evlerin ocak başında bulunur. Bolluk ve sağlık için yapıldıkları düşünülüyor.'),
    A('tunc_bilezik', 'Tunç Bilezik', 1, 110, 'orman', 'Takı & Süs', 'Tunç Çağı', 'bracelet', { a: '#b8873a', b: '#6f8f5e', c: '#e0b45a' },
      'Üzerinde dalga motifleri olan, yeşil pas tutmuş bir bilezik.',
      'Dalga motifi, Orman Krallığı\'nın göl kenarındaki ilk yerleşimine işaret ediyor olabilir.'),
    A('kandil', 'Pişmiş Toprak Kandil', 1, 80, 'orman', 'Seramik & Cam', 'Roma Dönemi', 'lamp', { a: '#c9784a', b: '#8f4d2c', c: '#e8a070' },
      'Zeytinyağıyla yakılan küçük bir kandil. Fitil deliği kararmış.',
      'Kandilin altındaki mühür, kasabanın yakınında eski bir çömlekçi atölyesi olduğunu kanıtlıyor.'),
    A('gumus_sikke', 'Gümüş Sikke', 1, 120, 'orman', 'Sikkeler', 'Orman Krallığı, MÖ 2. yy', 'coin', { a: '#c8ccd4', b: '#8a8f9a', c: '#f2f4f8' },
      'Parlak gümüşten, üzerinde baykuş figürü olan bir sikke.',
      'Baykuş bilgeliği simgeler. Bu sikke krallığın en parlak döneminde basılmış.'),
    A('amonit', 'Amonit Fosili', 1, 100, 'orman', 'Fosil & Doğa', 'Jura, 150 milyon yıl önce', 'ammonite', { a: '#b49a74', b: '#7f6a4c', c: '#d8c29c' },
      'Spiral kabuklu kadim bir deniz canlısı. Bu ormanın bir zamanlar deniz olduğunun kanıtı.',
      'Amonitler dinozorlarla aynı dönemde yaşadı. Kasabanın altındaki kireçtaşı eski bir deniz tabanı.', { fossil: true }),
    A('bahar_vazosu', 'Çiçekli Vazo', 1, 150, 'orman', 'Seramik & Cam', 'Roma Dönemi', 'vase', { a: '#e8d6b0', b: '#b89a6a', c: '#d8455a' },
      'Üzerine bahar çiçekleri resmedilmiş zarif bir vazo. Yalnızca ilkbaharda, yumuşayan toprakta çıkar.',
      'Vazodaki çiçekler bugün kasabanın çevresinde açan gelinciklerle aynı tür.', { seasons: [0] }),
    A('gunes_tokasi', 'Güneş Tokası', 1, 160, 'orman', 'Takı & Süs', 'Orman Krallığı', 'brooch', { a: '#d8a42a', b: '#a87a1e', c: '#fff2b0' },
      'Güneş biçimli tunç bir pelerin tokası. Yaz sıcağında kuruyan toprakta ortaya çıkar.',
      'Yaz gündönümü törenlerinde rahiplerin taktığı bir toka. Tabletlerdeki güneş simgesine çok benziyor.', { seasons: [1] }),
    A('tunc_orak', 'Tunç Orak', 1, 140, 'orman', 'Araç & Silah', 'Tunç Çağı', 'sickle', { a: '#b8873a', b: '#7a4f2a', c: '#e0b45a' },
      'Hasat zamanı kullanılmış kavisli bir orak. Sonbaharda, yaprakların altında bulunur.',
      'Orak, ormanın bir zamanlar geniş buğday tarlalarıyla çevrili olduğunu gösteriyor.', { seasons: [2] }),
    A('ay_muskasi', 'Ay Taşı Muskası', 2, 300, 'orman', 'Takı & Süs', 'Bilinmeyen Uygarlık', 'amulet', { a: '#cfe3f2', b: '#7f9ab8', c: '#ffffff' },
      'Kar altındaki kalıntılarda bulunan, soluk mavi ışıldayan bir muska.',
      'Ay taşı karanlıkta hafifçe parlıyor. Mağaradaki kristallerle aynı mineral.', { seasons: [3], spotOnly: 'kar' }),
    A('tablet_gunes', 'Yazıtlı Tablet: Güneş', 2, 260, 'orman', 'Yazıt & Mühür', 'Bilinmeyen Uygarlık', 'tablet', { a: '#a8a090', b: '#787060', c: '#f2c14e' },
      'Ortasında güneş simgesi olan, bilinmeyen bir yazıyla kaplı taş tablet.',
      'Defne\'nin çözümü: "Güneş doğduğunda ilk kapı aydınlanır." Bu dil bilinen hiçbir dile benzemiyor.', { tablet: true }),
    A('tablet_ay', 'Yazıtlı Tablet: Ay', 2, 260, 'orman', 'Yazıt & Mühür', 'Bilinmeyen Uygarlık', 'tablet', { a: '#9aa0a8', b: '#6a7078', c: '#cfe3ff' },
      'Hilal simgeli bir tablet. Yazılar tek bir elden çıkmış gibi.',
      '"Ay yükseldiğinde yol taşın altından geçer." Tabletler bir yeri tarif ediyor olabilir.', { tablet: true }),
    A('tablet_yildiz', 'Yazıtlı Tablet: Yıldız', 2, 260, 'orman', 'Yazıt & Mühür', 'Bilinmeyen Uygarlık', 'tablet', { a: '#a09a90', b: '#706a60', c: '#bfe8ff' },
      'Yedi köşeli yıldız simgeli bir tablet.',
      '"Yıldızlar sayıldığında mühür çözülür." Üç tablet birlikte okununca mağaradaki mühürlü kapıyı anlatıyor.', { tablet: true }),
    A('silindir_muhur', 'Silindir Mühür', 2, 260, 'orman', 'Yazıt & Mühür', 'Tunç Çağı', 'seal', { a: '#6f8a8f', b: '#45595e', c: '#9bb5ba' },
      'Kil üzerinde yuvarlanınca bir avcı sahnesi bırakan oyma taş mühür.',
      'Mühürdeki avcı, Orman Krallığı\'nın efsanevi kurucusu Kral Meşe olabilir.'),
    A('tunc_hancer', 'Tunç Hançer', 2, 240, 'orman', 'Araç & Silah', 'Tunç Çağı', 'dagger', { a: '#c48f4a', b: '#7a5530', c: '#efe2c4' },
      'Kabzası kemik kakmalı, törenlerde kullanılmış olabilecek bir hançer.',
      'Hiç kullanılmamış olması, bir savaşçıya değil bir rahibe ait olduğunu düşündürüyor.'),
    A('balik_fosili', 'Balık Fosili', 2, 200, 'orman', 'Fosil & Doğa', 'Kretase, 90 milyon yıl önce', 'fishfossil', { a: '#b8ab92', b: '#7d705a', c: '#efe6d0' },
      'Kayaya gömülmüş kusursuz bir balık iskeleti.',
      'Yüzgeçlerin biçimi, balığın sığ ve sıcak bir lagünde yaşadığını gösteriyor.', { fossil: true }),
    A('orman_maskesi', 'Taş Orman Maskesi', 3, 600, 'orman', 'Gizem', 'Bilinmeyen Uygarlık', 'mask', { a: '#6f8f6a', b: '#44603f', c: '#c9e0a0' },
      'Yosun yeşili taştan oyulmuş, gözleri yarı kapalı gizemli bir maske.',
      'Maskenin iç yüzünde tabletlerdeki yazı var: "Bekçi uyur, şehir bekler."'),
    A('altin_yuzuk', 'Altın Mühür Yüzüğü', 3, 550, 'orman', 'Takı & Süs', 'Orman Krallığı', 'ring', { a: '#e8b83a', b: '#a87a1e', c: '#d8354a' },
      'Kraliyet arması taşıyan ağır bir altın yüzük.',
      'Yüzük krallığın son kraliçesi Ela\'ya ait. Kraliçenin mezarı hiç bulunamadı.'),
    A('tanrica_bustu', 'Orman Tanrıçası Büstü', 4, 1500, 'orman', 'Heykel & Figür', 'Bilinmeyen Uygarlık', 'bust', { a: '#e8e2d4', b: '#b0a898', c: '#7fae6a' },
      'Saçları yapraklarla örülmüş, huzurlu yüzlü mermer büst.',
      'Tabandaki yazı: "Toprağın altındaki şehrin annesi." Kayıp Şehir\'e dair ilk somut ipucu.'),
    // ---------------- KÜÇÜK MAĞARA ----------------
    A('tas_balta', 'Cilalı Taş Balta', 1, 130, 'magara', 'Araç & Silah', 'Neolitik Dönem', 'axe', { a: '#5f8a6a', b: '#3c5c44', c: '#9cc2a2' },
      'Yeşil taştan cilalanmış, sapı için oyuk açılmış bir balta başı.',
      'Bu taş uzak dağlardan getirilmiş; demek ki ticaret çok eskiye dayanıyor.'),
    A('boncuk_kolye', 'Taş Boncuk Kolye', 1, 140, 'magara', 'Takı & Süs', 'Neolitik Dönem', 'necklace', { a: '#c8553d', b: '#3d7fd9', c: '#f2c14e' },
      'Renkli taş boncuklardan dizilmiş bir kolye.',
      'Boncukların bazıları denizden gelen kabuklardan yapılmış.'),
    A('tunc_ayna', 'Tunç Ayna', 2, 320, 'magara', 'Takı & Süs', 'Tunç Çağı', 'mirror', { a: '#c9a050', b: '#7d6230', c: '#f2e2a8' },
      'Bir yüzü cilalı, diğer yüzünde dans eden figürler olan el aynası.',
      'Aynaların ruhları yansıttığına inanılır, bu yüzden mezarlara konurmuş.'),
    A('ayi_kafatasi', 'Mağara Ayısı Kafatası', 2, 280, 'magara', 'Fosil & Doğa', 'Buzul Çağı', 'skull', { a: '#e6dcc4', b: '#a89a7c', c: '#3a2a2a' },
      'Devasa bir mağara ayısının kafatası.',
      'Mağara ayıları 25.000 yıl önce yok oldu. Bu mağarada kış uykusuna yatmışlar.', { fossil: true }),
    A('kristal_idol', 'Kristal İdol', 3, 700, 'magara', 'Heykel & Figür', 'Bilinmeyen Uygarlık', 'idol', { a: '#cfeaf2', b: '#8ab8c8', c: '#ffffff' },
      'Saf kuvarstan oyulmuş, içinden ışık geçen küçük bir idol.',
      'İdolün içine kazınmış yedi yıldız, tabletteki yıldızla birebir aynı.'),
    A('gunes_diski', 'Güneş Diski', 4, 2000, 'magara', 'Gizem', 'Bilinmeyen Uygarlık', 'disc', { a: '#f2c14e', b: '#b8862a', c: '#fff2b0' },
      'Mühürlü odada bulunan, ortasında yedi ışınlı güneş olan altın disk.',
      'Disk bir anahtar gibi tasarlanmış. Kenarındaki çentikler Kayıp Şehir\'in kapısına uyuyor olabilir.', { fixed: true }),
    A('harita_1', 'Kayıp Şehir Haritası I', 4, 0, 'magara', 'Gizem', 'Bilinmeyen Uygarlık', 'map', { a: '#d8c08a', b: '#8f7344', c: '#c8553d' },
      'Deri üzerine çizilmiş bir harita parçası. Kum tepeleri ve bir sütun çizili.',
      'Haritadaki semboller Çöl Harabeleri\'ni gösteriyor. Diğer parçalar karla ve ateşle işaretlenmiş yerlerde.', { fixed: true, noSell: true }),
    // ---------------- ÇÖL HARABELERİ ----------------
    A('amfora', 'Amfora', 1, 160, 'col', 'Seramik & Cam', 'Antik Ticaret Çağı', 'amphora', { a: '#d08a5a', b: '#8f5534', c: '#3b2416' },
      'Şarap ve zeytinyağı taşımak için kullanılan iki kulplu küp.',
      'Amforanın üzerindeki mühür, çölün bir zamanlar büyük bir ticaret yolu olduğunu gösteriyor.'),
    A('cam_sise', 'Antik Cam Şişe', 1, 170, 'col', 'Seramik & Cam', 'Antik Ticaret Çağı', 'bottle', { a: '#7fc8b8', b: '#4a8a7a', c: '#c8f0e8' },
      'Kumun içinde yüzyıllarca kırılmadan kalmış yeşilimsi bir cam şişe.',
      'Cam yapımı bu bölgede çok erken başlamış. Şişede parfüm kalıntıları bulundu.'),
    A('altin_sikke', 'Altın Sikke', 2, 300, 'col', 'Sikkeler', 'Kum Krallığı, MÖ 5. yy', 'coin', { a: '#f2c14e', b: '#a87a1e', c: '#fff2b0' },
      'Üzerinde akrep figürü olan ağır bir altın para.',
      'Akrep, Kum Krallığı\'nın koruyucusuydu. Bu sikkeler yalnızca saray hazinesinde bulunur.'),
    A('skarabe', 'Kum Böceği Muskası', 2, 350, 'col', 'Takı & Süs', 'Kum Krallığı', 'scarab', { a: '#3d7fd9', b: '#2a4f8a', c: '#f2c14e' },
      'Mavi sırlı taştan yapılmış böcek biçimli bir muska.',
      'Böcek, güneşi her sabah yeniden doğurduğuna inanılan kutsal bir figür.'),
    A('civi_tablet', 'Çivi Yazılı Tablet', 2, 380, 'col', 'Yazıt & Mühür', 'Kum Krallığı', 'tablet', { a: '#c8a070', b: '#8a6a40', c: '#5a3a22' },
      'Kil üzerine çivi yazısıyla yazılmış bir ticaret kaydı.',
      'Tablet, "kuzeydeki ormanın altındaki şehre" giden kervanlardan söz ediyor.'),
    A('kehribar', 'Böcekli Kehribar', 3, 650, 'col', 'Fosil & Doğa', '40 milyon yıl önce', 'amber', { a: '#e8a02a', b: '#a8641a', c: '#fff2b0' },
      'İçinde kusursuzca korunmuş bir böcek olan bal rengi kehribar.',
      'Böcek bugün nesli tükenmiş bir türe ait. Kehribar o zamanlar bölgenin ormanlık olduğunu gösteriyor.', { fossil: true }),
    A('tunc_migfer', 'Tunç Miğfer', 3, 800, 'col', 'Araç & Silah', 'Kum Krallığı', 'helmet', { a: '#c48f4a', b: '#7a5530', c: '#c8553d' },
      'Yanak korumalı, tepesi sorguçlu bir tunç miğfer.',
      'Miğfer, Kum Krallığı muhafızlarının taşıdığı tipte. İçinde bir isim kazılı: "Kapının Bekçisi".'),
    A('kral_maskesi', 'Altın Kral Maskesi', 4, 3000, 'col', 'Gizem', 'Kum Krallığı', 'mask', { a: '#f2c14e', b: '#a87a1e', c: '#3d7fd9' },
      'Lapis gözlü, ağır altından bir ölüm maskesi.',
      'Maske Kum Krallığı\'nın son kralına ait. Tacındaki yedi ışın Güneş Diski\'yle aynı.'),
    A('harita_2', 'Kayıp Şehir Haritası II', 4, 0, 'col', 'Gizem', 'Bilinmeyen Uygarlık', 'map', { a: '#e0c890', b: '#8f7344', c: '#3d7fd9' },
      'İkinci harita parçası. Karlı bir dağ ve bir mağara ağzı çizili.',
      'Parçalar birleştiğinde bir yol beliriyor: Donmuş Dağ\'dan geçip Volkanik Bölge\'ye uzanan bir yol.', { fixed: true, noSell: true }),
  ];

  const byId = {};
  LIST.forEach((a, i) => { a.idx = i; byId[a.id] = a; });

  AK.Artifacts = {
    RARITY, CATS, REGIONS, LIST, byId,
    get: id => byId[id],
    rarityName: r => RARITY[r].id,
    rarityCol: r => RARITY[r].col,
    pool(region, rar, season, opts) {
      opts = opts || {};
      return LIST.filter(a => a.region === region && a.rar === rar && !a.fixed &&
        (!a.seasons || a.seasons.includes(season)) &&
        (!a.spotOnly || a.spotOnly === opts.spot) &&
        (opts.fossil === undefined || !!a.fossil === opts.fossil));
    },
  };
})();
